version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  docker: circleci/docker@2.1.2

jobs:
  build:
    executor: 'aws-ecr/default'
    steps:
      - checkout
      - aws-ecr/build-image:
          dockerfile: Dockerfile
          no-output-timeout: 10m
          tag: 'latest'
          region: ${AWS_DEFAULT_REGION}
          registry-id: AWS_ACCOUNT_ID
          skip-when-tags-exist: false
          push-image: false
          repo: $CIRCLE_PROJECT_REPONAME

workflows:
  build_and_push_image:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
          executor-class: medium

      - build:
          context: prod-us
          filters:
            branches:
              only:
                - /feature\/.*/

      - aws-ecr/build-and-push-image:
          context: prod-us
          executor: aws-ecr/default
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-cli-version: latest
          create-repo: false
          repo: $CIRCLE_PROJECT_REPONAME
          tag: 'latest'
          dockerfile: Dockerfile
          no-output-timeout: 20m
          public-registry: false
          push-image: true
          region: ${AWS_DEFAULT_REGION}
          registry-id: AWS_ACCOUNT_ID
          repo-scan-on-push: true
          skip-when-tags-exist: false
          filters:
            branches:
              only:
                - master
